/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prova_josebergonsi.DAO.DestinoDAO;
import prova_josebergonsi.model.Destino;
import tela.TelaCusto;

/**
 *
 * @author joseb
 */
public class TelaDestino extends javax.swing.JDialog {

    private DestinoDAO destinoDAO;

    public TelaDestino(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        destinoDAO = new DestinoDAO();
        try {
            carregaTable(destinoDAO.getAll());
        } catch (SQLException ex) {
            Logger.getLogger(TelaDestino.class.getName()).log(Level.SEVERE, null, ex);
        }
        btSalvar.setEnabled(false);
        tfcodigods.setEnabled(false);
        desabilitaCampos(false);
        habilitaFiltroCodigo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfdatafim = new javax.swing.JTextField();
        tfcodigods = new javax.swing.JTextField();
        tfdescricaods = new javax.swing.JTextField();
        tfdatainicio = new javax.swing.JTextField();
        tfvalortotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDestino = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btFiltrar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        rbcodigo = new javax.swing.JRadioButton();
        tfcodigoft = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbdescricao = new javax.swing.JRadioButton();
        tfdescricaoft = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btVerCustos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Data Fim");

        jLabel3.setText("Valor Total");

        jLabel4.setText("Data Inicio");

        jLabel5.setText("Descricao");

        tfcodigods.setEditable(false);
        tfcodigods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigodsActionPerformed(evt);
            }
        });

        tfdescricaods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdescricaodsActionPerformed(evt);
            }
        });

        tableDestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descrição", "Data Inicio", "Data Fim", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(tableDestino);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btFiltrar.setText("Filtrar");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        rbcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcodigoActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo");

        jLabel7.setText("Descricao");

        rbdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdescricaoActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar Tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btVerCustos.setText("Ver Custos");
        btVerCustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerCustosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbcodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfcodigoft, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbdescricao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdescricaoft, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(29, 29, 29)
                                                .addComponent(tfcodigods, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfdescricaods, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfdatainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfvalortotal)
                                    .addComponent(tfdatafim)
                                    .addComponent(btVerCustos, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfcodigods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfdatafim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfdescricaods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdatainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVerCustos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbcodigo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfcodigoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbdescricao)
                            .addComponent(tfdescricaoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btFiltrar)
                    .addComponent(btRemover))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdescricaodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdescricaodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdescricaodsActionPerformed

    private void tfcodigodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigodsActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
 
            salvar();
        if (validaCampos() == true) {
            salvar();
        }
           
       

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
        filtrar();
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        remover();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void rbcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcodigoActionPerformed
        habilitaFiltroCodigo();
    }//GEN-LAST:event_rbcodigoActionPerformed

    private void rbdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdescricaoActionPerformed
        habilitaFiltroNome();
    }//GEN-LAST:event_rbdescricaoActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novo();
    }//GEN-LAST:event_btNovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     atualizarTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btVerCustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerCustosActionPerformed
 TelaCusto dialog = new TelaCusto(new javax.swing.JFrame(),true);
 dialog.setVisible(true);
 

    }//GEN-LAST:event_btVerCustosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDestino dialog = new TelaDestino(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void carregaTable(List<Destino> clienteList) {
        if (clienteList == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tableDestino.getModel();
        model.setRowCount(0);
        for (Destino c : clienteList) {
            model.addRow(new Object[]{c.getCodigo_destino(), c.getDescricao_destino(), c.getData_ini(), c.getData_fim(), c.getVltotal_dest()});
        }
    }

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVerCustos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbcodigo;
    private javax.swing.JRadioButton rbdescricao;
    private javax.swing.JTable tableDestino;
    private javax.swing.JTextField tfcodigods;
    private javax.swing.JTextField tfcodigoft;
    private javax.swing.JTextField tfdatafim;
    private javax.swing.JTextField tfdatainicio;
    private javax.swing.JTextField tfdescricaods;
    private javax.swing.JTextField tfdescricaoft;
    private javax.swing.JTextField tfvalortotal;
    // End of variables declaration//GEN-END:variables

       private void salvar() {

        try {
          
            Destino destino = new Destino();
            destino.setCodigo_destino(Integer.parseInt(tfcodigods.getText()));
            destino.setDescricao_destino(tfdescricaods.getText());
            destino.setData_ini(java.sql.Date.valueOf(tfdatainicio.getText()));
            destino.setData_fim(java.sql.Date.valueOf(tfdatafim.getText()));
            destino.setVltotal_dest(Float.parseFloat(tfvalortotal.getText()));

            try {
limpaCampos();
                destinoDAO.save(destino);
                JOptionPane.showMessageDialog(null, "Destino Salvo com Sucesso");
              
                carregaTable(destinoDAO.getAll());
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Caracter Inválido");
        }
    }

    private void desabilitaCampos(boolean ativo) {
        tfcodigods.setEnabled(ativo);
        tfdescricaods.setEnabled(ativo);
        tfdatainicio.setEnabled(ativo);
        tfdatafim.setEnabled(ativo);
        tfvalortotal.setEnabled(ativo);
    }

    private void limpaCampos() {
        tfcodigods.setText("");
        tfdescricaods.setText("");
        tfdatainicio.setText("");
        tfdatafim.setText("");
        tfvalortotal.setText("");
    }

    private void filtrar() {
        try {
            if (rbcodigo.isSelected() && tfcodigoft.getText().trim().length() > 0) {
                Destino cliente = destinoDAO.getById(Integer.parseInt(tfcodigoft.getText()));
                List<Destino> clienteList = new ArrayList<>();
                clienteList.add(cliente);
                carregaTable(clienteList);
            } else if (rbdescricao.isSelected() && tfdescricaoft.getText().trim().length() > 0) {
                carregaTable(destinoDAO.getByName(tfdescricaoft.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "Informe qual filtro desejado para pesquisa");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void remover() {
        int linhaSelecionada = tableDestino.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Deve-se selecionar uma linha para ser removido");
            return;
        }
        int codigoRemover = (int) tableDestino.getValueAt(linhaSelecionada, 0);
        try {
            destinoDAO.delete(codigoRemover);
            JOptionPane.showMessageDialog(null, "Destino Removido com Sucesso!");
            carregaTable(destinoDAO.getAll());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void habilitaFiltroCodigo() {
        tfdescricaoft.setText("");
        tfdescricaoft.setEnabled(false);
        tfcodigoft.setEnabled(true);
    }

    private void habilitaFiltroNome() {
        tfcodigoft.setText("");
        tfcodigoft.setEnabled(false);
        tfdescricaoft.setEnabled(true);
    }

    private void novo() {
        try {
            tfcodigods.setText(String.valueOf(destinoDAO.getLastId()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        desabilitaCampos(true);
        btSalvar.setEnabled(true);
    }

   public Boolean validaCampos() {

        if (tfcodigods.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe um código para salvar.");
            return false;
        } else if (tfdescricaods.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe um Destino para salvar.");
            return false;
        } else if (tfdatainicio.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe uma Data Inicio para salvar.");
            return false;
        } else if (tfdatafim.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe uma Data fim para salvar.");
            return false;
        } else if (tfvalortotal.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe um Valor para salvar.");
            return false;
        }

        return true;
    }
        private void atualizarTabela() {
       try{
        carregaTable(destinoDAO.getAll());
        
    }catch(SQLException ex){
         Logger.getLogger(TelaCusto.class.getName()).log(Level.SEVERE, null, ex);
    }
}
        
}
