/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prova_josebergonsi.DAO.CustoDAO;
import prova_josebergonsi.model.Custo;

/**
 *
 * @author joseb
 */
public class TelaCusto extends javax.swing.JDialog {

    private CustoDAO custoDAO;
    public TelaCusto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(null);
        custoDAO = new CustoDAO();
        try {
            carregaTable(custoDAO.getAll());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCusto.class.getName()).log(Level.SEVERE, null, ex);
        }
        btSalvar.setEnabled(false);
        tfCodigoCs.setEnabled(false);
        desabilitaCampos(false);
        habilitaFiltroCodigo();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCodigoCs = new javax.swing.JTextField();
        tfDsCusto = new javax.swing.JTextField();
        tfTipoCusto = new javax.swing.JTextField();
        tfVlCusto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCusto = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btFiltrar = new javax.swing.JButton();
        tfCodigoFt = new javax.swing.JTextField();
        tfDsft = new javax.swing.JTextField();
        rbDescricaocusto = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbCodigoCusto = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo ");

        jLabel2.setText("Valor Custo");

        jLabel3.setText("Descricao");

        jLabel4.setText("Tipo");

        tfCodigoCs.setEditable(false);

        tbCusto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descricao", "Tipo", "Valor Custo"
            }
        ));
        jScrollPane1.setViewportView(tbCusto);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btFiltrar.setText("Filtrar");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        rbDescricaocusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDescricaocustoActionPerformed(evt);
            }
        });

        jLabel5.setText("Descricao");

        jLabel6.setText("Codigo");

        rbCodigoCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoCustoActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar Tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCodigoCusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigoFt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(rbDescricaocusto)
                        .addGap(18, 18, 18)
                        .addComponent(tfDsft, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCodigoCs)
                            .addComponent(tfDsCusto)
                            .addComponent(tfTipoCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfVlCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(tfCodigoCs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfVlCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addComponent(tfDsCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTipoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoFt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDsft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbDescricaocusto)
                    .addComponent(jLabel5)
                    .addComponent(rbCodigoCusto)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btRemover)
                    .addComponent(btNovo)
                    .addComponent(btFiltrar)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        remover();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
      salvar();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
        filtrar();
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
       novo();
    }//GEN-LAST:event_btNovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       atualizarTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbCodigoCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoCustoActionPerformed
      habilitaFiltroCodigo();
    }//GEN-LAST:event_rbCodigoCustoActionPerformed

    private void rbDescricaocustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDescricaocustoActionPerformed
        habilitaFiltroNome();
    }//GEN-LAST:event_rbDescricaocustoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCusto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCusto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCusto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCusto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCusto dialog = new TelaCusto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
        private void carregaTable(List<Custo> custoList) {
        if (custoList == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tbCusto.getModel();
        model.setRowCount(0);
        for (Custo c : custoList) {
            model.addRow(new Object[]{c.getCodigo(), c.getDescricao(), c.getTipoCusto(), c.getValorCusto()});
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCodigoCusto;
    private javax.swing.JRadioButton rbDescricaocusto;
    private javax.swing.JTable tbCusto;
    private javax.swing.JTextField tfCodigoCs;
    private javax.swing.JTextField tfCodigoFt;
    private javax.swing.JTextField tfDsCusto;
    private javax.swing.JTextField tfDsft;
    private javax.swing.JTextField tfTipoCusto;
    private javax.swing.JTextField tfVlCusto;
    // End of variables declaration//GEN-END:variables

           private void remover() {
        int linhaSelecionada = tbCusto.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Deve-se selecionar uma linha para ser removido");
            return;
        }
        int codigoRemover = (int) tbCusto.getValueAt(linhaSelecionada, 0);
        try {
            custoDAO.delete(codigoRemover);
            JOptionPane.showMessageDialog(null, "Custo Removido com Sucesso!");
            carregaTable(custoDAO.getAll());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
 private void salvar() {
        try {
            Custo custo = new Custo();
            custo.setCodigo(Integer.parseInt(tfCodigoCs.getText()));
            custo.setDescricao(tfDsCusto.getText());
            custo.setTipoCusto(Integer.parseInt(tfTipoCusto.getText()));
            custo.setValorCusto(Float.parseFloat(tfVlCusto.getText()));
          

            try {

                custoDAO.save(custo);
                JOptionPane.showMessageDialog(null, "Custo Salvo com Sucesso");
                limpaCampos();
                carregaTable(custoDAO.getAll());
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Caracter Inválido");
        }
    }
  private void limpaCampos() {
        tfCodigoCs.setText("");
        tfDsCusto.setText("");
        tfTipoCusto.setText("");
        tfVlCusto.setText("");
       
    }
      private void filtrar() {
        try {
            if (rbCodigoCusto.isSelected() && tfCodigoFt.getText().trim().length() > 0) {
                Custo custo = custoDAO.getById(Integer.parseInt(tfCodigoFt.getText()));
                List<Custo> custoList = new ArrayList<>();
                custoList.add(custo);
                carregaTable(custoList);
            } else if (rbDescricaocusto.isSelected() && tfDsft.getText().trim().length() > 0) {
                carregaTable(custoDAO.getByName(tfDsft.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "Informe qual filtro desejado para pesquisa");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
      
          private void desabilitaCampos(boolean ativo) {
        tfCodigoCs.setEnabled(ativo);
        tfDsCusto.setEnabled(ativo);
        tfTipoCusto.setEnabled(ativo);
        tfVlCusto.setEnabled(ativo);
       
    }

    private void novo() {
        try {
            tfCodigoCs.setText(String.valueOf(custoDAO.getLastId()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        desabilitaCampos(true);
        btSalvar.setEnabled(true);
    }

    private void habilitaFiltroCodigo() {
        tfDsft.setText("");
        tfDsft.setEnabled(false);
        tfCodigoFt.setEnabled(true);
    }

    private void habilitaFiltroNome() {
        tfCodigoFt.setText("");
        tfCodigoFt.setEnabled(false);
        tfDsft.setEnabled(true);
    }

    public Boolean validaCampos() {

        if (tfCodigoCs.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe um código para salvar.");
            return false;
        } else if (tfDsCusto.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe um Custo para salvar.");
            return false;
        } else if (tfTipoCusto.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe um Tipo para salvar.");
            return false;
        } else if (tfVlCusto.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Informe um Valor para salvar.");
            return false;
        }
        return true;
    }
    private void atualizarTabela() {
       try{
        carregaTable(custoDAO.getAll());
        
    }catch(SQLException ex){
         Logger.getLogger(TelaCusto.class.getName()).log(Level.SEVERE, null, ex);
    }
}
}


